#######################################################################################
# A default configuration that will be loaded for all jupyter books
# Users are expected to override these values in their own `_config.yml` file.
# This is also the "master list" of all allowed keys and values.

#######################################################################################
# Book settings
title                       : "Fokker-Planck – Intro"
author                      : "Alexandre René and Alexander van Meegen"
copyright                   : "2022"
logo                        : ""
exclude_patterns            : [_build, Thumbs.db, "**.DS_Store", "**.ipynb_checkpoints",

                               ".*", "**.egg-info", "*.mypy_cache", "**__pycache__",
                               "**.smt", src, lib, env, "env-*", "README.md"]
    # NB: 'data' only excludes the top-level directory.
    #     To exclude all subdirs named 'data', would would do "**data"
    #     (which we don't want, since there is a 'data' subpackage)
only_build_toc_files        : false

#######################################################################################
# Execution settings
execute:
  execute_notebooks         : "cache"
  exclude_patterns          : [envs, env]    # A list of patterns to *skip* in execution (e.g. a notebook that takes a really long time).
                                        # Note that the 'skip-execution' tag is now available, if only particular cells are long to compute.
  allow_errors              : true
  timeout                   : 30

#######################################################################################
# Parse and render settings
parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    # - html_admonition
    - html_image
    # - linkify
    # - replacements
    # - smartquotes
    - substitution

#######################################################################################
# HTML-specific settings
html:
  use_repository_button: true
  use_issues_button: true

#######################################################################################
# LaTeX-specific settings
latex:
  latex_engine              : xelatex  # one of 'pdflatex', 'xelatex' (recommended for unicode), 'luatex', 'platex', 'uplatex'
  use_jupyterbook_latex     : true # use jupyterbook-latex for pdf builds as default

#######################################################################################
# Launch button settings
#launch_buttons:
#  notebook_interface        : jupyterlab  # The interface interactive links will activate ["classic", "jupyterlab"]

repository:
  url: https://github.com/alcrene/fokker-planck-brief-intro
  path_to_book              : ""  # A path to your book's folder, relative to the repository root.
  branch                    : main  # Which branch of the repository should be used when creating links

#######################################################################################
# Advanced and power-user settings

bibtex_bibfiles:
  - references.bib

sphinx:
  local_extensions          :   # A list of local extensions to load by sphinx specified by "name: path" items
  config                    :   # key-value pairs to directly over-ride the Sphinx configuration
    nb_custom_formats:
        .py:
            - jupytext.reads
            - fmt: py

    # Use MathJax 3, which is much better for math-heavy documents
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js   # Use MathJax v3 instead of default v2
    mathjax3_config:
      # This dictionary is assigned as-is to window.MathJax; https://docs.mathjax.org/en/latest/input/tex/extensions/mathtools.html
      tex:
        packages:
          "[+]": ["mathtools"]
        macros: {
          bm: ["{\\boldsymbol #1}",1],
        }
        # tags: 'none'
      loader:
        load: ['[tex]/mathtools']

    bibtex_reference_style: author_year